name: commit stage
on: push
jobs:
  build:
    name: build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go mod vendor
      - run: go vet ./...
      - run: go build -mod vendor -o app.go cmd/app/main.go

